### ISSUE TITLE
Sometimes exponential back-off reports more connected peers than the number of bootstraps it connects to

### ISSUE THREAD

**Issue by mwyzhao** [Multi-Tier-Cloud/common#1]
![ebnotworking](https://user-images.githubusercontent.com/21133720/77219506-d9700c00-6b0c-11ea-84ec-54521d96c660.JPG)

**Comment by t-lin** [comment]
Where is the screenshot taken from? Is it from after `NewNode()` is called?

**Comment by mwyzhao** [comment]
This output is from the bootstraps section of NewNode() if I remember correctly

**Comment by t-lin** [comment]
Hasn't appeared in a while, closing for now.
