### ISSUE TITLE
Add ability to advertise service after p2p node creation

### ISSUE THREAD

**Issue by t-lin** [Multi-Tier-Cloud/common#2]
Right now it looks like the advertised service (rendezvous string) can only be applied in the `Config` struct supplied to `NewNode()`.  Perhaps have a method to create a node first and explicitly call advertise after.

**Comment by mwyzhao** [comment]
solved by https://github.com/Multi-Tier-Cloud/common/commit/94c7b474e3b4ca9f1b6a20930a3f4aaa5da6dc74
